FROM node:20.18 AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

RUN npm rebuild esbuild

COPY . .

RUN npm run build && cp -r dist /dist-artifact

LABEL stage=frontend-build

FROM nginx:latest

COPY --from=build /dist-artifact /dist-artifact

EXPOSE 80
