FROM node:20 AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN rm -rf node_modules package-lock.json
RUN npm install

COPY . .
RUN npm run build

FROM nginx:latest

COPY ./default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80